//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSTOK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblmusteri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblmusteri()
        {
            this.aktiflik = true;
            this.tblstokhareketleri = new HashSet<tblstokhareketleri>();
        }
    
        public int MüsteriId { get; set; }
        public string MusteriAd { get; set; }
        public string MusteriSoyad { get; set; }
        public string sehir { get; set; }
        public Nullable<decimal> bakiye { get; set; }
        public string MusteriEmail { get; set; }
        public string MusteriTelefon { get; set; }
        public string MusteriAdres { get; set; }
        public Nullable<bool> aktiflik { get; set; }
        public Nullable<System.DateTime> MusteriEklenmeTarihi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblstokhareketleri> tblstokhareketleri { get; set; }
    }
}
