//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSTOK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblstokhareketleri
    {
        public int HareketId { get; set; }
        public Nullable<int> MusteriId { get; set; }
        public Nullable<int> PersonelId { get; set; }
        public Nullable<int> İşlemId { get; set; }
        public Nullable<decimal> fiyat { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public string Aciklama { get; set; }
        public Nullable<int> UrunId { get; set; }
        public Nullable<int> Miktar { get; set; }
    
        public virtual tblislemler tblislemler { get; set; }
        public virtual tblmusteri tblmusteri { get; set; }
        public virtual tblpersonel tblpersonel { get; set; }
        public virtual tblurunler tblurunler { get; set; }
    }
}
