//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCSTOK.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblurunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblurunler()
        {
            this.aktiflik = true;
            this.tblstokhareketleri = new HashSet<tblstokhareketleri>();
        }
    
        public int UrunId { get; set; }
        public string UrunAd { get; set; }
        public string marka { get; set; }
        public Nullable<int> StokAdet { get; set; }
        public Nullable<decimal> alisfiyat { get; set; }
        public Nullable<decimal> satisfiyat { get; set; }
        public Nullable<int> KategoriId { get; set; }
        public Nullable<bool> aktiflik { get; set; }
        public Nullable<System.DateTime> EklenmeTarihi { get; set; }
    
        public virtual tblkategori tblkategori { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblstokhareketleri> tblstokhareketleri { get; set; }
    }
}
